FROM alpine:3.17
RUN apk add --no-cache \
  apache2 \
  binutils \
  go \
  haproxy \
  memcached \
  nginx \
  nodejs \
  perl \
  php-cli \
  php-fpm \
  postfix \
  python3 \
  redis \
  ruby \
  samba \
  varnish
