FROM centos:7
RUN yum -y install \
  binutils \
  haproxy \
  httpd \
  memcached \
  perl \
  php-cli \
  php-fpm \
  postfix \
  python2 \
  python3 \
  ruby \
  samba \
  tomcat \
  && yum clean all