FROM rockylinux:8
RUN yum -y install \
  binutils \
  golang \
  haproxy \
  httpd \
  memcached \
  nginx \
  nodejs \
  perl \
  php-cli \
  php-fpm \
  postfix \
  python2 \
  python3 \
  redis \
  ruby \
  samba \
  varnish \
  && yum clean all