name: Build container images
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        target: ["ubuntu2204_full"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 並列でContainer Imageをビルド
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.target }}
          push: true
          tags: witchcraze/samples:${{ matrix.target }}

# 参考 : https://qiita.com/tomoyk/items/ab4d55cd1735bb2b579a
